kind: PersistentVolume
apiVersion: v1
metadata:
  name: stsweb-pv-volume
  labels:
    type: local
spec:
  storageClassName: stsweb-storage-class
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/stsdata"
