apiVersion: v1
kind: Service
metadata:
  name: my-np-service
  labels:
    app: my-nginx
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 32660
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: my-nginx
