# kubectl exec -it mypod -- bash
#
# tail -n 1 /etc/foo/my-group/my*
# ==> /etc/foo/my-group/my-apssword <==
# 1f2d1e2e67df
# ==> /etc/foo/my-group/my-username <==
# admin

apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: redis
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: mysecret
      items:
      - key: username
        path: my-group/my-username
      - key: password
        path: my-group/my-apssword
