apiVersion: v1
kind: Service
metadata:
  name: stsweb
  labels:
    app: stsweb
spec:
  ports:
  - port: 80
    name: http
  clusterIP: None
  selector:
    app: stsweb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stsweb
spec:
  selector:
    matchLabels:
      app: stsweb # has to match .spec.template.metadata.labels
  serviceName: "stsweb"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: stsweb # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: stsweb
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: stsweb
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "stsweb-storage-class"
      resources:
        requests:
          storage: 1Gi
